In [ ]:
import os
import numpy as np
import pandas as pd

print(os.getcwd())

data = np.load("../../data/highfidelity/1000_clean.npz", allow_pickle=True)

for key in data.keys():
    arr = data[key]
    print(f"'{key}': shape={arr.shape}, dtype={arr.dtype}")
    #print(f"   → {arr[:3]}")   # print first 3 elements as a preview

/global/home/users/caterinafrau/PEDS_NT/modules/PEDS_utils

FileNotFoundError: [Errno 2] No such file or directory: '../FILES/600_samples.csv'

In [15]:
keff = data['keffs']
print(len(keff), keff.min(), keff.max())

1082 0.8003338 1.1997865

In [3]:
names = data["param_names"]
print("Parameter names:", names)

Parameter names: ['r0_b4c_rod_outer_radius' 'r0_b4c_rod_cr_fraction'
 'r1_fuel_annulus_outer_radius' 'r1_fuel_annulus_enrichment'
 'r1_fuel_annulus_f_mod' 'r2_water_outer_radius']

In [3]:
params = data['params']

print(f"Global min: {params.min():.6f}  (should be >= 0)")
print(f"Global max: {params.max():.6f}  (should be <= 1)")

# Turn the 6-parameter array into a readable DataFrame
df = pd.DataFrame(data['params_raw'], columns=data['param_names'])
df['keff'] = data['keffs']
df.head(10)   # renders as a formatted table in Jupyter

Global min: 0.000000  (should be >= 0)
Global max: 1.000000  (should be <= 1)

,r0_b4c_rod_outer_radius,r0_b4c_rod_cr_fraction,r1_fuel_annulus_outer_radius,r1_fuel_annulus_enrichment,r1_fuel_annulus_f_mod,r2_water_outer_radius,keff
0,11.556512,0.905372,38.880562,5.439324,0.494988,71.823174,1.112346
1,10.155149,0.989356,30.743412,3.212645,0.478271,63.706596,0.955000
2,6.746740,0.259062,27.659996,2.439992,0.531828,51.189171,0.970983
3,9.239386,0.154959,24.044960,9.240696,0.340715,71.098923,0.989303
4,5.641399,0.728658,30.927868,7.010476,0.561978,74.213715,1.180168
5,5.664272,0.542680,29.829443,3.224965,0.500477,53.980515,1.033199
6,8.588620,0.308692,36.589199,9.558659,0.413275,70.272766,1.163234
7,7.573712,0.907653,33.205585,8.634194,0.511727,53.078213,1.168308
8,9.390934,0.651482,25.131966,8.290689,0.441943,52.427223,0.997596
9,5.800577,0.151721,24.384308,6.999584,0.571559,60.387241,1.124147

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("../FILES/28june_newTD.csv")

keff = df['keff']
print(len(keff), keff.min(), keff.max())
bins = np.arange(0.5, 1.5, 0.05)

binned_counts = pd.cut(keff, bins=bins, include_lowest=True).value_counts().sort_index()

print(binned_counts)

150 0.6407003138668785 1.414611595847999
keff
(0.499, 0.55]     0
(0.55, 0.6]       0
(0.6, 0.65]       1
(0.65, 0.7]       4
(0.7, 0.75]       1
(0.75, 0.8]       4
(0.8, 0.85]       8
(0.85, 0.9]       4
(0.9, 0.95]      15
(0.95, 1.0]      13
(1.0, 1.05]      10
(1.05, 1.1]      13
(1.1, 1.15]      19
(1.15, 1.2]      19
(1.2, 1.25]      13
(1.25, 1.3]       9
(1.3, 1.35]      10
(1.35, 1.4]       5
(1.4, 1.45]       2
Name: count, dtype: int64

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("../NTcode_config_data/lhs_analysis_outputs/merged_good_lhs.csv")

keff = df['keff']
print(len(keff), keff.min(), keff.max())

2931 0.5542749366111364 1.4267691410163734

In [4]:
# keep only keff values between 0.8 and 1.2
keff_filtered = df.loc[df["keff"].between(1.25, 1.5)]

print("Number of samples in [0.5, 0.8]:", len(keff_filtered))

#print("the head is ", keff_filtered.head())
print("showing ")
keff_filtered[["keff", "r1_fuel_annulus_outer_radius", "r1_fuel_annulus_f_mod", "r0_b4c_rod_outer_radius", "r0_b4c_rod_cr_fraction" ]].head(15)

Number of samples in [0.5, 0.8]: 26
showing

,keff,r1_fuel_annulus_outer_radius,r1_fuel_annulus_f_mod,r0_b4c_rod_outer_radius,r0_b4c_rod_cr_fraction
1,1.268343,39.279836,0.603535,2.872357,0.273343
6,1.309675,42.476037,0.576329,4.971289,0.606964
25,1.319209,39.773616,0.586428,3.184543,0.246405
30,1.344029,37.151625,0.751176,5.103449,0.313351
33,1.356064,39.497461,0.732055,5.411420,0.475183
34,1.253637,37.531655,0.682156,3.909025,0.866170
54,1.268171,36.420349,0.543950,2.737989,0.358849
63,1.315002,36.711092,0.747477,5.046776,0.674605
67,1.275739,31.149103,0.615076,2.276672,0.775192
82,1.266206,43.495613,0.584362,3.942791,0.101262
89,1.315208,42.593227,0.563394,2.399478,0.921261
91,1.254134,27.508047,0.694858,2.857517,0.534084
92,1.274169,38.423541,0.780182,3.146165,0.306628
95,1.320435,42.170739,0.571385,2.674341,0.327459
105,1.330406,44.563053,0.623143,3.048433,0.704909

In [7]:
# keep only keff values between 0.8 and 1.2
fmod = df.loc[df["r1_fuel_annulus_f_mod"].between(0.65, 0.8)]

print("Number of samples in [0.5, 0.8]:", len(fmod))

#print("the head is ", keff_filtered.head())
print("showing ")
fmod[["keff", "r1_fuel_annulus_outer_radius", "r1_fuel_annulus_f_mod", "r0_b4c_rod_outer_radius", "r0_b4c_rod_cr_fraction" ]].tail(15)

Number of samples in [0.5, 0.8]: 55
showing

,keff,r1_fuel_annulus_outer_radius,r1_fuel_annulus_f_mod,r0_b4c_rod_outer_radius,r0_b4c_rod_cr_fraction
120,1.224099,27.863455,0.665644,2.163932,0.449375
122,1.301594,44.637063,0.663209,5.031184,0.639402
123,1.168903,40.747664,0.670694,4.829025,0.066594
124,1.279933,40.041714,0.768689,4.572466,0.527286
127,0.921201,13.321023,0.746654,3.268451,0.623653
129,1.387541,43.819253,0.769850,1.434135,0.995568
130,1.303800,43.260163,0.710131,2.549656,0.509310
132,1.400958,43.712370,0.757654,5.161668,0.400899
133,0.993091,20.181093,0.675018,5.076338,0.718708
134,1.201704,32.071850,0.714358,3.529946,0.441240
135,0.941117,17.725152,0.795767,5.511533,0.575915
139,1.132684,19.134544,0.658864,2.442864,0.201773
140,1.001526,24.196485,0.665248,5.637813,0.264195
141,0.657209,10.391413,0.778693,1.901044,0.125231
149,1.083022,37.568913,0.655518,1.331864,0.310364